# Site
name: "Petr Bouda"
title: "Petr Bouda"
description: "Java/JVM Enthusiast and Speaker"
meta_description: "Java/JVM Enthusiast and Speaker"
logo: 'assets/images/logo.png'
baseurl:
include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-seo-tag

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge